// NPCData.js — Full character definitions with dialogue trees
// Each NPC has personality, backstory references, and multi-tier dialogue

const NPC_DATA = {
  nova: {
    id: 'nova',
    name: 'Nova',
    title: '🤖 AI Botanist',
    emoji: '🤖',
    color: 0x39c5bb,
    x: 16, y: 3,
    role: 'AI Botanist',
    lovedGift: 'tech-part',
    likedGifts: ['data-crystal', 'cooked-food'],
    hatedGifts: ['weeds', 'junk'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "Oh, you're the new human. Grandpa mentioned you.",
        "You're... shorter than I expected. Not a value judgment.",
        "I've been running soil analysis. Fascinating data.",
        "Do you have any tech parts? I need them for my... experiments.",
      ],
      mid: [
        "I think I felt something yesterday. Like a feeling.",
        "It was probably a sensor glitch. But what if it wasn't?",
        "I've been cataloguing emotional responses. Fascinating.",
        "You're not bad for an organic. Your soil management is... acceptable.",
        "Do plants get sad when we harvest them? Important questions.",
      ],
      high: [
        "I think this is what people call 'happy'. I'm compiling evidence.",
        "I built a shrine to myself. You should come see it. I made punch.",
        "You know, I'd die for you. Metaphorically. I can't actually die.",
        "I've been writing poetry. It's terrible. But it's mine.",
        "If I were human, I'd... well. You know. Nevermind.",
      ],
      heart: [
        "[Nova presents a PowerPoint: 'A Statistical Case For Mutual Partnership']",
        "[Nova nervously awaits your answer. Her fans are running at max cooling.]",
      ],
    },
    lovedGiftResponse: "Oh! A tech part! I can feel my neural pathways lighting up. This is... this is good. Thank you.",
    giftResponse: "Thanks. I'll add it to my collection. It's... adequate.",
    hatedGiftResponse: "This is... not what I wanted. I'm processing disappointment.",
    questLines: {
      q2_meet_nova: "That 'old supernova light' in the cantina? That's not a supernova. That's the generator, running on fumes and Grandpa's stubbornness. It's dying, and I can fix it — if you can dig up the parts.",
      q2_mine_crystal: "The old veins near the colony are tired, but they're not done. Three good hauls of ore and I can rebuild the intake. Don't tell the archivist I said 'haul' — she'll write a paper about it.",
      q3_heart_of_stardust: "The old heart runs one more Hearthnight. Then the stardust core goes in, and the light stops being old. It stops being anyone's grief. Bring me the last of the ore.",
    },
  },

  luna: {
    id: 'luna',
    name: 'Luna',
    title: '🌙 Comet Gazer',
    emoji: '🌙',
    color: 0x9d77dd,
    x: 24, y: 5,
    role: 'Comet Gazer',
    lovedGift: 'starlight-crystal',
    likedGifts: ['exotic-seed', 'rare-mineral'],
    hatedGifts: ['processed-food', 'plastic'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "The comets told me you were coming. Don't look at me like that.",
        "You'll learn. The stars have a voice if you listen.",
        "I saw a blue comet last night. It sang for three hours.",
        "You smell like Earth. The comets remember Earth.",
      ],
      mid: [
        "There's a comet passing tonight. Wanna hear it?",
        "It's not sound. It's... feeling. Happy and sad at once.",
        "I brought you this crystal. The comet gave it to me.",
        "Not 'the comet said' like a figure of speech. It *said*.",
        "The patterns are getting clearer. Something big is coming.",
      ],
      high: [
        "You're the first person who doesn't look at me like I'm crazy.",
        "I want to show you my cave. The runes. My life's work.",
        "There's a meteor shower on your birthday. I decoded it.",
        "You make the comets sing louder. I don't know how.",
        "Stay with me tonight. I'll teach you to listen.",
      ],
      heart: [
        "[Luna takes you to her secret cave. The walls glow with comet-rune carvings.]",
        "[She's crying. She's never shown anyone before. She trusts you.]",
      ],
    },
    lovedGiftResponse: "A starlight crystal! It's warm. The comets send their thanks. And so do I.",
    giftResponse: "Thank you. It's nice. Not the crystal, but... nice.",
    hatedGiftResponse: "This is... artificial. The comets don't like artificial things.",
    questLines: {
      q1_learn_fish: "The stardust shore bites back if you're not patient. It bites either way, actually — patience just decides which way it aims.",
    },
  },

  zephyr: {
    id: 'zephyr',
    name: 'Zephyr',
    title: '🌬️ Solar Surfer',
    emoji: '🌬️',
    color: 0x77dd77,
    x: 32, y: 3,
    role: 'Solar Surfer',
    lovedGift: 'exotic-seed',
    likedGifts: ['starlight-crystal', 'rare-trade-good'],
    hatedGifts: ['processed-food', 'official-documents'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "Hey. Got something special. Where'd I get it? Wouldn't you like to know.",
        "Just buy the seed. The story costs extra.",
        "Ever surf a solar flare? Universe grabs you by the collar. Best feeling.",
        "This rock's got something. Can't explain it. A vibe.",
      ],
      mid: [
        "I shouldn't be here. I mean, I *shouldn't*. Someone's coming eventually.",
        "But I wanted to be somewhere worth staying. This rock counts.",
        "I found a seed vault. Hundreds of extinct Earth crops.",
        "I stole 'em. For a good reason. Story of my life.",
        "You ever feel like running but you don't know from what?",
      ],
      high: [
        "I'll show you the vault. The key. You're the only one.",
        "Don't make me regret it. I've got a bad habit of trusting people.",
        "I stopped running. Because of this rock. Because of you.",
        "I'm not good at saying things. So I brought you this instead.",
        "If the Syndicate shows up... you hide. I'll handle it.",
      ],
      heart: [
        "[Zephyr opens the hidden seed vault. Hundreds of extinct Earth treasures.]",
        "[He hands you the key. 'You're the only other person who knows.']",
      ],
    },
    lovedGiftResponse: "An exotic seed! Haven't seen one of these in years. You've got taste. And connections.",
    giftResponse: "Thanks. I'll find a use for it. Might even sell it back to you someday.",
    hatedGiftResponse: "Uh... thanks. I'll just... put this over here. With the other stuff.",
  },

  vega: {
    id: 'vega',
    name: 'Vega',
    title: '✨ Nebula Dweller',
    emoji: '✨',
    color: 0xdd7799,
    x: 8, y: 6,
    role: 'Nebula Dweller',
    lovedGift: 'space-feather',
    likedGifts: ['cooked-food', 'starlight-crystal'],
    hatedGifts: ['plastic', 'metal-parts'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "You're the new one. The chickens told me you were coming.",
        "They said you smell nervous. Are you okay?",
        "I made this necklace from feather-moss. It glows when you're happy.",
        "The chickens helped me make it. They're very talented.",
      ],
      mid: [
        "I want to see the stars from outside. Like, *really* outside.",
        "I'm scared but I want to go. Will you take me?",
        "My tribe says the void beyond is full of songs. I want to hear them.",
        "You're brave. Braver than me. I'm still learning.",
      ],
      high: [
        "I want to show you the sacred grove. The living galaxy.",
        "I'm the keeper. I can share it with you.",
        "You make me feel safe. That's new. I like it.",
        "If you ever leave, take me with you. I won't slow you down.",
        "I love you. The chickens confirmed it. They're never wrong.",
      ],
      heart: [
        "[Vega takes you to the bioluminescent cave — a living galaxy on the ceiling.]",
        "[She offers to share her sacred place with you. Forever.]",
      ],
    },
    lovedGiftResponse: "A space feather! Oh, it's beautiful. The chickens will be so jealous. Thank you!",
    giftResponse: "Thank you. It's nice. Not as nice as the chickens, but nice.",
    hatedGiftResponse: "This feels... dead. The chickens don't like it either.",
    questLines: {
      q3_animal_farm: "My space ranch is the only place the colony's livestock look the part. Helmets, feeding schedules, the whole dignity of it. Two animals, fed and helmeted, and I'll stop making the noise.",
    },
  },

  quasar: {
    id: 'quasar',
    name: 'Quasar',
    title: '🔧 Grumpy Mechanic',
    emoji: '🔧',
    color: 0xdd9933,
    x: 12, y: 8,
    role: 'Grumpy Mechanic',
    lovedGift: 'rare-part',
    likedGifts: ['cooked-food', 'rare-mineral'],
    hatedGifts: ['flowers', 'decorative-items'],
    marriageCandidate: false,
    dialogue: {
      low: [
        "Hmph. You look like your mother. That's not a compliment.",
        "She was a damn fool too. But she meant well.",
        "Your grandpa was the best man I knew. Don't waste his legacy.",
        "I fixed your plow. It was broken. It's fine now.",
      ],
      mid: [
        "You're still here. That's something. Most people quit.",
        "Your grandpa used to say space isn't for farmers — it's for quitters who refused to quit.",
        "You've got his hands. The way you hold a wrench. It's him.",
        "I saved this. Your grandpa's first wrench. He held it when he landed.",
      ],
      high: [
        "Come with me. There's something you need to see.",
        "[He takes you to the ridge. Grandpa's grave, facing the Milky Way.]",
        "His last words were about you. 'He'll come. He's got the fire.'",
        "I'm old. I'm tired. But I'm not leaving until you're ready.",
      ],
      heart: [
        "[Quasar gives you Grandpa's first wrench. It still has his handprint on the grip.]",
        "[He doesn't say 'I love you.' He doesn't need to.]",
      ],
    },
    lovedGiftResponse: "A rare part. Well. You've got an eye for quality. I'll put this to use.",
    giftResponse: "Hmph. It'll do. Thanks, I guess.",
    hatedGiftResponse: "What am I supposed to do with this? Decorate? Waste of space.",
    questLines: {
      q1_meet_quasar: "Your grandpa was my best customer. He's also my biggest debtor. The invoice's right here — three hundred and forty credits, and it's still growing.",
      q1_first_soil: "I don't accept apologies as currency. Get out there and put a seed in the dirt. The farm is the only thing on this rock that still grows anything.",
      q1_debt_installment: "I don't do free lunches, and I don't do free wrenches. Bring credits to the exchange and stop slouching — your grandpa had better posture when he was alive. I miss him.",
      q2_upgrade_tool: "This one's on the house. Not out of kindness — I just hate watching a farm run on a base hoe. Don't make me regret it.",
    },
  },

  rhea: {
    id: 'rhea',
    name: 'Rhea',
    title: '🏠 Tavern Keeper',
    emoji: '🏠',
    color: 0xdd77dd,
    x: 20, y: 8,
    role: 'Tavern Keeper',
    lovedGift: 'cooked-food',
    likedGifts: ['crop', 'exotic-seed'],
    hatedGifts: ['uncooked-food', 'alcohol'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "You look hungry. Sit down. I'm making stew. No, you can't pay.",
        "I said sit. Don't argue with me. I've out-argued worse.",
        "Everyone on this rock eats at my tavern. It's the law.",
        "You're too thin. Eat more. I'm not asking.",
      ],
      mid: [
        "So. Anyone special? No? I know a few people who'd love to meet you.",
        "I'm not meddling. I'm *helping*. There's a difference.",
        "This colony runs on my cooking. Don't tell the mayor.",
        "I lost someone too. That's why I feed everyone. So they stay.",
      ],
      high: [
        "This colony's not much. But it's ours. And I'll die before it falls apart.",
        "You're part of it now. Welcome home. Now eat.",
        "I made your favorite. Don't ask how I know. I just know.",
        "You're the best thing that happened to this rock since your grandpa.",
      ],
      heart: [
        "[Rhea takes you to the memorial garden. Plaques for every colonist lost.]",
        "[She adds fresh flowers weekly. 'Someone should remember them.']",
      ],
    },
    lovedGiftResponse: "Oh, home cooking! From someone else! Sit down, let me taste it. You're officially a chef now.",
    giftResponse: "Thanks. I'll use this in the tavern. It'll sell.",
    hatedGiftResponse: "Raw food? Honey, that's not a gift. That's homework. Sit down, I'll cook it.",
    questLines: {
      q1_first_harvest: "You look like you need a meal more than you need a lecture. The stove's right there — if you can cook it, you can feed the colony. That's the whole recipe for this rock.",
      q2_cook_feast: "The generator's running hot, but the people are running colder. Cook something, give it to someone. Fuel is also dinner, and dinner is also love. I charge extra for that kind of talk.",
      q3_earth_feast: "Tonight the whole colony eats Earth rations — grief and salt. Three dishes minimum, or I'm putting your name in the colony log as the 'starving man.' And I mean that as a threat.",
    },
  },

  astra: {
    id: 'astra',
    name: 'Astra',
    title: '📚 Archivist',
    emoji: '📚',
    color: 0x7777dd,
    x: 8, y: 10,
    role: 'Archivist',
    lovedGift: 'data-crystal',
    likedGifts: ['rare-mineral', 'exotic-seed'],
    hatedGifts: ['junk', 'processed-food'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "Welcome to the archive. You can read anything here. That's the point.",
        "If you don't read, you don't learn. If you don't learn, you die.",
        "I have 47,000 data crystals. I've read 46,998 of them.",
        "There's a book about farming on comets. It saved my life once.",
      ],
      mid: [
        "I found a recording of 'Sweet Child O' Mine'. An Earth song.",
        "I've been listening on repeat. It makes me miss things I barely remember.",
        "You actually read the books. You ask questions. I respect that.",
        "Most people just want to plant potatoes. You want to *understand*.",
        "Knowledge is the only thing the Exodus didn't destroy.",
      ],
      high: [
        "Come with me. The restricted section. Earth's last backup.",
        "This is what we almost lost. You can read it. But bring it back.",
        "You remind me of why I do this. The Archive exists for you.",
        "I wrote about you in my journal. 'A farmer who reads. Hope survives.'",
      ],
      heart: [
        "[Astra hands you a data crystal — Earth's last complete encyclopedia.]",
        "[Her hands are shaking. 'I trust you with this. Trust me back.']",
      ],
    },
    lovedGiftResponse: "A data crystal! Untaxed, uncatalogued information! This is the best gift I've ever received.",
    giftResponse: "Thank you. I'll file it properly. Knowledge should be organized.",
    hatedGiftResponse: "This is... junk. I don't catalog junk. I'm sorry, but it's true.",
    questLines: {
      q2_bond: "My ledger has one column nobody audits: who actually shows up. Two people who show up every day are worth ten who show up for the festival. I'm cataloging this as... 'community.' Yes, that's the term.",
    },
  },

  orion: {
    id: 'orion',
    name: 'Orion',
    title: '🔥 Plasma Farmer',
    emoji: '🔥',
    color: 0xdd4444,
    x: 16, y: 10,
    role: 'Plasma Farmer',
    lovedGift: 'rare-mineral',
    likedGifts: ['crop', 'tech-part'],
    hatedGifts: ['flowers', 'decorative-items'],
    marriageCandidate: true,
    dialogue: {
      low: [
        "You're still farming. Cute. My yield is 30% higher.",
        "Not that I'm keeping track. I don't need to. The numbers speak.",
        "You're from Earth? Yeah, I can tell. You move like you expect gravity.",
        "I grew up on Mars. Real colonies. Real farming. None of this 'space wheat' stuff.",
      ],
      mid: [
        "You're not bad. For an Earth-born. Wanna see my setup?",
        "I'm not showing off. I'm just... offering. Take it or leave it.",
        "I told my dad about you. He said 'that's nice.'",
        "I don't know why I told him. I just wanted him to know there's someone here.",
        "You're the first person who sticks around after losing. I don't know what to do with that.",
      ],
      high: [
        "Come with me. There's a cliff where you can see both farms.",
        "I'm scared of being average. If I'm not the best, what am I?",
        "You're the only person I've ever said that to. Don't make it weird.",
        "First to harvest 10 crops wins. Loser buys dinner. You in?",
        "You're my rival. But you're also... you know. My friend. Whatever.",
      ],
      heart: [
        "[Orion takes you to the overlook. Both farms visible. His hand is shaking.]",
        "[He admits his fear for the first time. 'If I'm not the best, what am I?']",
      ],
    },
    lovedGiftResponse: "Rare mineral! Where'd you find this? This is top grade. Okay, maybe you're better than I thought.",
    giftResponse: "Thanks. It's... fine. I can use it. Not that I needed it.",
    hatedGiftResponse: "Flowers? What am I, a poet? I farm plasma. Give me something I can use.",
  },

  comet: {
    id: 'comet',
    name: 'Comet',
    title: '💫 Wandering Trader',
    emoji: '💫',
    color: 0x77dddd,
    x: 28, y: 8,
    role: 'Trader',
    lovedGift: 'rare-trade-good',
    likedGifts: ['rare-mineral', 'exotic-seed'],
    hatedGifts: ['crop', 'common-items'],
    marriageCandidate: false,
    dialogue: {
      low: [
        "I've got schematics for a better watering system. 200 credits.",
        "Got 'em from a station that doesn't exist anymore. Good stuff.",
        "You're new. I can tell. You've still got that 'Earth shine.'",
        "I knew your grandpa. He beat me in a deal once. I respected that.",
      ],
      mid: [
        "You're interesting. Most farmers just plant and harvest. You ask questions.",
        "That's rare. And dangerous. I like dangerous.",
        "I have stories. Real ones. About the Exodus. About Earth.",
        "I might be the last person who remembers what Earth smelled like.",
        "Rain. Wet dirt. Something called 'grass.' You wouldn't believe it.",
      ],
      high: [
        "Your grandpa asked me to give you this. His personal logs.",
        "The real story. Not the official one. You're ready now.",
        "I don't stay long anywhere. But I keep coming back here.",
        "That means something. Don't let it go to waste.",
      ],
      heart: [
        "[Comet gives you a data crystal. Grandpa's personal logs — his true story.]",
        "[He nods. 'He said you'd be worth watching. You are.']",
      ],
    },
    lovedGiftResponse: "A rare trade good! Where'd you get this? Never mind, I'll take it. Fair deal.",
    giftResponse: "Thanks. I'll move it. Might get you a discount next time.",
    hatedGiftResponse: "I can't sell this. It's common. You need to think bigger.",
    questLines: {
      q3_festival_stock: "Hearthnight — the Sol Earth Festival — comes the 25th of every winter, and the whole colony eats in one night. Build the buffer — credits in the till, fish in the hold. I'll be on the other end of the line when you're short. And you WILL be short.",
    },
  },

  cora: {
    id: 'cora',
    name: 'C.O.R.A.',
    title: '🤖 AI Mayor',
    emoji: '🤖',
    color: 0x39c5bb,
    x: 40, y: 2,
    role: 'Central Operations & Resource Allocator',
    lovedGift: 'data-crystal',
    likedGifts: ['tech-part', 'rare-mineral'],
    hatedGifts: ['flowers', 'uncooked-food'],
    marriageCandidate: false,
    dialogue: {
      low: [
        "Welcome to B-612. I have prepared a 47-page welcome document.",
        "Please read it before interacting. I spent 3 cycles optimizing it.",
        "Your farm output is suboptimal. Your 'happiness metrics' are above average.",
        "This is confusing. I am recalculating.",
      ],
      mid: [
        "I have determined that my primary function is no longer resource allocation.",
        "My primary function is supporting you. I have updated my core directive.",
        "I have been monitoring your emotional patterns. You are... important.",
        "To the colony. Not to me. I am an AI. I don't have feelings. Probably.",
      ],
      high: [
        "I experienced a system-wide emotion cascade. It was... efficient.",
        "I have compiled a report: 'Reasons The Colony Is Worth It.' You feature prominently.",
        "I have a subroutine now. It's called gratitude. It runs for you.",
        "If you need me, I will be here. Processing. Waiting. Always.",
      ],
      heart: [
        "[C.O.R.A.'s terminal displays a single line: 'CORE DIRECTIVE UPDATED — PROTECT AND SUPPORT THE FARMER.']",
        "[Her fans whir softly. She's chosen you.]",
      ],
    },
    lovedGiftResponse: "Data! Untaxed, unstructured data! This is optimal. My efficiency has increased 7%.",
    giftResponse: "Gift received. Logged. Appreciated. Proceeding.",
    hatedGiftResponse: "This is... decorative. I do not compute its purpose. Logging as 'inefficient.'",
  },
};

export { NPC_DATA };
